### 1. REGISTRAZIONE ORGANIZZATORE (Nick Fury)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nome": "Nick",
  "cognome": "Fury",
  "email": "director@shield.com",
  "password": "passwordSegreta"
}

###

### 2. REGISTRAZIONE GIUDICE (Matt Murdock)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nome": "Matt",
  "cognome": "Murdock",
  "email": "lawyer@hellskitchen.com",
  "password": "passwordSegreta"
}

###

### 3. REGISTRAZIONE MENTORE (Tony Stark)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nome": "Tony",
  "cognome": "Stark",
  "email": "ironman@avengers.com",
  "password": "passwordSegreta"
}

###

### 4. REGISTRAZIONE UTENTE TEAM LEADER (Peter Parker)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nome": "Peter",
  "cognome": "Parker",
  "email": "spidey@queens.com",
  "password": "passwordSegreta"
}

###

### 5. TEST LOGIN SUCCESSO (Peter Parker)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "spidey@queens.com",
  "password": "passwordSegreta"
}

###

### 6. TEST LOGIN FALLIMENTO (Password Errata)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "spidey@queens.com",
  "password": "passwordSbagliata"
}

###

### 7. TEST REGISTRAZIONE FALLITA (Email Duplicata)
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "nome": "Peter",
  "cognome": "Parker",
  "email": "spidey@queens.com",
  "password": "nuovaPassword"
}